library(faraway)
data(sat)
plot(sat$takers, sat$total)
plot(sat$salary, sat$total)
plot(sat$ratio, sat$total)
h0a = lm(total ~ takers + ratio + salary, data = sat)
summary(h0a)
h0 = lm(total ~ takers + ratio, data = sat)
anova(h0, h0a)
h00 = lm(total ~ 1, data = sat)
anova(h00, h0a)
conf = confint(h0a, "salary", level = 0.95)
conf
conf = confint(h0a, "salary", level = 0.99)
conf
library(ellipse)
plot(ellipse(h0a, c('ratio', 'salary'), level = 0.95), type = "l", xlim = c(-10,1))
points(0, 0, pch = 1)
points(h0a$coef['ratio'], h0a$coef['salary'], pch = 18)
abline(v = confint(h0a)[3,], lty = 2)
abline(h = confint(h0a)[4,], lty = 2)
ha = lm(total ~ takers + ratio + salary + expend, data = sat)
summary(ha)
h000 = lm(total ~ takers, data = sat)
anova(h000, ha)
grid = seq(25,52,0.01)
pred = predict(h0a, data.frame(salary = grid, takers = 35, ratio = 17), interval = "confidence")
pred1 = predict(h0a, data.frame(salary = grid, takers = 35, ratio = 17), interval = "prediction")
pre = cbind(pred, pred1)
matplot(grid, pre, lty = c(1,2,2), col = 1, type = "l", xlab = "salary", ylab = "total")
