library(faraway)
data(infmort)
infmortm = na.omit(infmort)
library(MASS)
y = lm(mortality ~ region * income, data = infmortm)
summary(y)
require(ggplot2)
ggplot(aes(x=income,y=mortality),data=infmortm)+geom_point()+facet_wrap(~
region)+geom_smooth(method="lm")
ggplot(aes(x=log(income),y=mortality),data=infmortm)+geom_point()+facet_wrap(~
region)+geom_smooth(method="lm")
ylog = lm(mortality ~ log(income) + region + log(income):region, data = infmortm)
summary(ylog)
anova(ylog)
# Box-Cox method for data
boxcox(ylog, plotit = T)
boxcox(ylog, plotit = T, lambda = seq(-1, 0, by = 0.1))
ybc = lm(mortality^(-0.25) ~ log(income) + region + log(income):region, data = infmortm)
summary(ybc)
anova(ybc)
# drop interaction term
ydr = lm(mortality^(-0.25) ~ log(income) + region, data = infmortm)
summary(ydr)
# after the other has been taken into account
drop1(ydr, test="F")
# diagnostics
plot(residuals(ydr) ~ fitted(ydr), pch = unclass(infmortm$region), xlab = "fitted", ylab = "residuals")
abline(h = 0)
ri = rstudent(ydr)
qqnorm(ri, ylab = "Residuals")
qqline(ri)
cook = cooks.distance(ydr)
plot(dfbeta(ydr)[,1], ylab = "Change in beta0 coef")
abline(h=0)
identify(dfbeta(ydr)[,1])
plot(dfbeta(ydr)[,2], ylab = "Change in beta1 coef")
abline(h=0)
identify(dfbeta(ydr)[,2])
plot(dfbeta(ydr)[,3], ylab = "Change in beta2 coef")
abline(h=0)
identify(dfbeta(ydr)[,3])
plot(dfbeta(ydr)[,4], ylab = "Change in beta3 coef")
abline(h=0)
identify(dfbeta(ydr)[,4])
plot(dfbeta(ydr)[,5], ylab = "Change in beta4 coef")
abline(h=0)
identify(dfbeta(ydr)[,5])
infmortm1 = infmortm[-c(27),]
infmortm1 = infmortm[-c(25),]
ydr1 = lm(mortality^(-0.25) ~ log(income) + region, data = infmortm1)
summary(ydr1)
# regression lines
plot(mortality^(-0.25) ~ log(income), infmortm, pch = as.numeric(infmortm$region))
abline(0.138, 0.031)
abline(0.138+0.110, 0.031, lty = 2)
abline(0.138+0.066, 0.031, lty = 5)
abline(0.138+0.044, 0.031, lty = 7)